#!/usr/bin/env bash

set -e

npm install

pushd node_modules/vscode-markdown-languageserver
../.bin/pkg out/node/main.js -t node16-macos-x64,node16-macos-arm64
popd

rm -rf bin
mkdir bin

echo "Moving binaries to bin"
mv node_modules/vscode-markdown-languageserver/vscode-markdown-languageserver-arm64 bin/markdown-language-server-darwin-aarch64
mv node_modules/vscode-markdown-languageserver/vscode-markdown-languageserver-x64 bin/markdown-language-server-darwin-x86_64

gzip bin/markdown-language-server-darwin-aarch64
gzip bin/markdown-language-server-darwin-x86_64
