name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    name: Build binary
    runs-on:
      - self-hosted
      - bundle
    env:
      MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
      MACOS_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
    steps:
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Create binaries
        run: script/build

      - name: Upload aarch64 binaries to workflow run
        uses: actions/upload-artifact@v2
        with:
          name: markdown-language-server-darwin-aarch64.gz
          path: bin/markdown-language-server-darwin-aarch64.gz

      - name: Upload x86_64 binaries to workflow run
        uses: actions/upload-artifact@v2
        with:
          name: markdown-language-server-darwin-x86_64.gz
          path: bin/markdown-language-server-darwin-x86_64.gz

      - uses: softprops/action-gh-release@v1
        name: Upload binaries to release if release tag
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          draft: true
          files: bin/*
          overwrite: true
          body: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
